# -*- coding: utf-8 -*-#
# Python     : Python 2.7
# -------------------------------------------------------
# NAME       : fkcon
# Describe   : 需要bake的列表(修改自 MaxToMaya_kami (T:\X3_RawData\X3_MayaTools\python\MaxToMaya_kami))
# version    : v0.01
# Author     : linhuan
# Email      : hanhong@papegames.net
# DateTime   : 2022/7/12__21:33
# -------------------------------------------------------
def bk_ctrl():
    return {"fkcon":[u'FKHip_L',
            u'FKToes_R',
            u'FKAnkle_R',
            u'FKKnee_R',
            u'FKHip_R',
            u'FKMiddleFinger1_R',
            u'FKToes_L',
            u'FKAnkle_L',
            u'FKKnee_L',
            u'FKIndexFinger3_L',
            u'FKIndexFinger2_L',
            u'FKIndexFinger1_L',
            u'FKThumbFinger3_L',
            u'FKPinkyFinger3_L',
            u'FKPinkyFinger2_L',
            u'FKPinkyFinger1_L',
            u'FKCup_L',
            u'FKRingFinger1_R',
            u'FKPinkyFinger3_R',
            u'FKPinkyFinger2_R',
            u'FKPinkyFinger1_R',
            u'FKElbow_R',
            u'FKShoulder_R',
            u'FKRingFinger3_R',
            u'FKRingFinger2_R',
            u'FKThumbFinger3_R',
            u'FKThumbFinger2_R',
            u'FKThumbFinger1_R',
            u'FKMiddleFinger3_R',
            u'FKMiddleFinger2_R',
            u'FKCup_R',
            u'FKIndexFinger3_R',
            u'FKIndexFinger2_R',
            u'FKIndexFinger1_R',
            u'FKRingFinger3_L',
            u'FKRingFinger2_L',
            u'FKRingFinger1_L',
            u'FKWrist_L',
            u'FKElbow_L',
            u'FKShoulder_L',
            u'FKScapula_R',
            u'FKWrist_R',
            u'FKSpine1_M',
            u'FKRoot_M',
            u'FKScapula_L',
            u'FKNeck_M',
            u'FKNeckPart1_M',
            u'FKHead_M',
            u'FKChest_M',
            u'FKSpine3_M',
            u'FKSpine2_M',
            u'FKThumbFinger2_L',
            u'FKThumbFinger1_L',
            u'FKMiddleFinger3_L',
            u'FKMiddleFinger2_L',
            u'FKMiddleFinger1_L',
            u'RootX_M',
            u'FKPinkyFinger0_L',
            u'FKRingFinger0_L',
            u'FKMiddleFinger0_L',
            u'FKIndexFinger0_L',
            u'FKPinkyFinger0_R',
            u'FKRingFinger0_R',
            u'FKMiddleFinger0_R',
            u'FKIndexFinger0_R',
            u'FKToe_a_0_R',
            u'FKToe_a_1_R',
            u'FKToe_b_0_R',
            u'FKToe_b_1_R',
            u'FKToe_b_2_R',
            u'FKToe_c_0_R',
            u'FKToe_c_1_R',
            u'FKToe_c_2_R',
            u'FKToe_d_0_R',
            u'FKToe_d_1_R',
            u'FKToe_d_2_R',
            u'FKToe_e_0_R',
            u'FKToe_e_1_R',
            u'FKToe_e_2_R',
            u'FKToe_a_0_L',
            u'FKToe_a_1_L',
            u'FKToe_b_0_L',
            u'FKToe_b_1_L',
            u'FKToe_b_2_L',
            u'FKToe_c_0_L',
            u'FKToe_c_1_L',
            u'FKToe_c_2_L',
            u'FKToe_d_0_L',
            u'FKToe_d_1_L',
            u'FKToe_d_2_L',
            u'FKToe_e_0_L',
            u'FKToe_e_1_L',
            u'FKToe_e_2_L'
            ],
            "fk_js" :[u'FKAnkle_L', u'FKAnkle_R', u'FKWrist_L', u'FKWrist_R'],
            "ik_cons":[u'IKLeg_L', u'IKLeg_R', u'IKArm_L', u'IKArm_R'],
            "ik_vector" :[u'PoleLeg_L', u'PoleLeg_R', u'PoleArm_L', u'PoleArm_R']

            }

if __name__ == '__main__':
    print bk_ctrl()